apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-engine-monitor
  namespace: default

spec:
  replicas: 6
  selector:
    matchLabels:
      app: match-engine-monitor
  template:
    metadata:
      labels:
        app: match-engine-monitor
    spec:
      containers:
      - name: server
        image: 270863875638.dkr.ecr.us-east-1.amazonaws.com/test/match-engine-monitor:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: match-engine-monitor
  namespace: default
  labels:
    app: match-engine-monitor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: match-engine-monitor
  ports:
    - protocol: TCP
      name: http 
      port: 8080
      targetPort: 8080
