apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}-servicemonitor
  namespace: {{ .Values.name }}
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  endpoints:
    - port: http       
      path: /metrics
      interval: 15s

