apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: match-engine-monitor
  namespace: default
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: match-engine-monitor
  endpoints:
    - port: http       
      path: /metrics
      interval: 10s

